import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "../ui/organisms/NavBar";
import { Footer } from "../ui/atoms/Footer";

const montserrat = Montserrat({
	subsets: ["latin", "latin-ext"],
	variable: "--font-montserrat",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<html lang="en" className={montserrat.variable}>
			<body>
				<Header />
				<div className="min-h-full">{children}</div>
				<Footer />
				{modal}
			</body>
		</html>
	);
}
